version: '3.1'

services:
    kodivian:
        image: kodivian/server:latest
        restart: always
        environment:
            # Base Configuration
            - KODIVIAN_DATA_PATH=${KODIVIAN_DATA_PATH}
            - SERVER_PORT=${SERVER_PORT:-3030}
            - SERVER_HOST=${SERVER_HOST}
            - CONTEXT_PATH=${CONTEXT_PATH:-/kodivian}
            - PROXY_URL=${PROXY_URL}

            # DATABASE
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}

            # SECRET KEYS
            - SECRETKEY_STORAGE_TYPE=${SECRETKEY_STORAGE_TYPE}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - KODIVIAN_SECRETKEY_OVERWRITE=${KODIVIAN_SECRETKEY_OVERWRITE}
            - SECRETKEY_AWS_ACCESS_KEY=${SECRETKEY_AWS_ACCESS_KEY}
            - SECRETKEY_AWS_SECRET_KEY=${SECRETKEY_AWS_SECRET_KEY}
            - SECRETKEY_AWS_REGION=${SECRETKEY_AWS_REGION}
            - SECRETKEY_AWS_NAME=${SECRETKEY_AWS_NAME}

            # LOGGING
            - DEBUG=${DEBUG}
            - LOG_PATH=${LOG_PATH}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_ENABLED=${LOG_ENABLED:-true}
            - LOG_SYSTEM_ENABLED=${LOG_SYSTEM_ENABLED:-true}
            - LOG_WORKFLOWS_ENABLED=${LOG_WORKFLOWS_ENABLED:-true}
            - LOG_SERVICES_ENABLED=${LOG_SERVICES_ENABLED:-true}
            - LOG_STORAGE_ENABLED=${LOG_STORAGE_ENABLED:-true}
            - LOG_INFRASTRUCTURE_ENABLED=${LOG_INFRASTRUCTURE_ENABLED:-true}
            - LOG_SANITIZE_BODY_FIELDS=${LOG_SANITIZE_BODY_FIELDS}
            - LOG_SANITIZE_HEADER_FIELDS=${LOG_SANITIZE_HEADER_FIELDS}

            # CUSTOM TOOL/FUNCTION DEPENDENCIES
            - TOOL_FUNCTION_BUILTIN_DEP=${TOOL_FUNCTION_BUILTIN_DEP}
            - TOOL_FUNCTION_EXTERNAL_DEP=${TOOL_FUNCTION_EXTERNAL_DEP}
            - ALLOW_BUILTIN_DEP=${ALLOW_BUILTIN_DEP}

            # STORAGE
            - STORAGE_TYPE=${STORAGE_TYPE}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - S3_STORAGE_BUCKET_NAME=${S3_STORAGE_BUCKET_NAME}
            - S3_STORAGE_ACCESS_KEY_ID=${S3_STORAGE_ACCESS_KEY_ID}
            - S3_STORAGE_SECRET_ACCESS_KEY=${S3_STORAGE_SECRET_ACCESS_KEY}
            - S3_STORAGE_REGION=${S3_STORAGE_REGION}
            - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
            - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
            - GOOGLE_CLOUD_STORAGE_CREDENTIAL=${GOOGLE_CLOUD_STORAGE_CREDENTIAL}
            - GOOGLE_CLOUD_STORAGE_PROJ_ID=${GOOGLE_CLOUD_STORAGE_PROJ_ID}
            - GOOGLE_CLOUD_STORAGE_BUCKET_NAME=${GOOGLE_CLOUD_STORAGE_BUCKET_NAME}
            - GOOGLE_CLOUD_UNIFORM_BUCKET_ACCESS=${GOOGLE_CLOUD_UNIFORM_BUCKET_ACCESS}

            # SETTINGS
            - NUMBER_OF_PROXIES=${NUMBER_OF_PROXIES}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - CHATBOT_IFRAME_ORIGINS=${CHATBOT_IFRAME_ORIGINS}
            - KODIVIAN_FILE_SIZE_LIMIT=${KODIVIAN_FILE_SIZE_LIMIT}
            - SHOW_COMMUNITY_NODES=${SHOW_COMMUNITY_NODES}
            - DISABLE_KODIVIAN_TELEMETRY=${DISABLE_KODIVIAN_TELEMETRY}
            - DISABLED_NODES=${DISABLED_NODES}
            - MODEL_LIST_CONFIG_JSON=${MODEL_LIST_CONFIG_JSON}

            # AUTH PARAMETERS
            - APP_URL=${APP_URL}
            - JWT_AUTH_TOKEN_SECRET=${JWT_AUTH_TOKEN_SECRET}
            - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
            - JWT_ISSUER=${JWT_ISSUER}
            - JWT_AUDIENCE=${JWT_AUDIENCE}
            - JWT_TOKEN_EXPIRY_IN_MINUTES=${JWT_TOKEN_EXPIRY_IN_MINUTES}
            - JWT_REFRESH_TOKEN_EXPIRY_IN_MINUTES=${JWT_REFRESH_TOKEN_EXPIRY_IN_MINUTES}
            - EXPIRE_AUTH_TOKENS_ON_RESTART=${EXPIRE_AUTH_TOKENS_ON_RESTART}
            - EXPRESS_SESSION_SECRET=${EXPRESS_SESSION_SECRET}
            - PASSWORD_RESET_TOKEN_EXPIRY_IN_MINS=${PASSWORD_RESET_TOKEN_EXPIRY_IN_MINS}
            - PASSWORD_SALT_HASH_ROUNDS=${PASSWORD_SALT_HASH_ROUNDS}
            - TOKEN_HASH_SECRET=${TOKEN_HASH_SECRET}
            - SECURE_COOKIES=${SECURE_COOKIES}

            # EMAIL
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - SMTP_SECURE=${SMTP_SECURE}
            - ALLOW_UNAUTHORIZED_CERTS=${ALLOW_UNAUTHORIZED_CERTS}
            - SENDER_EMAIL=${SENDER_EMAIL}

            # ENTERPRISE
            - LICENSE_URL=${LICENSE_URL}
            - KODIVIAN_LICENSE_KEY=${KODIVIAN_LICENSE_KEY}
            - OFFLINE=${OFFLINE}

            # METRICS COLLECTION
            - POSTHOG_PUBLIC_API_KEY=${POSTHOG_PUBLIC_API_KEY}
            - ENABLE_METRICS=${ENABLE_METRICS}
            - METRICS_PROVIDER=${METRICS_PROVIDER}
            - METRICS_INCLUDE_NODE_METRICS=${METRICS_INCLUDE_NODE_METRICS}
            - METRICS_SERVICE_NAME=${METRICS_SERVICE_NAME}
            - METRICS_OPEN_TELEMETRY_METRIC_ENDPOINT=${METRICS_OPEN_TELEMETRY_METRIC_ENDPOINT}
            - METRICS_OPEN_TELEMETRY_PROTOCOL=${METRICS_OPEN_TELEMETRY_PROTOCOL}
            - METRICS_OPEN_TELEMETRY_DEBUG=${METRICS_OPEN_TELEMETRY_DEBUG}

            # PROXY
            - GLOBAL_AGENT_HTTP_PROXY=${GLOBAL_AGENT_HTTP_PROXY}
            - GLOBAL_AGENT_HTTPS_PROXY=${GLOBAL_AGENT_HTTPS_PROXY}
            - GLOBAL_AGENT_NO_PROXY=${GLOBAL_AGENT_NO_PROXY}

            # QUEUE CONFIGURATION
            - MODE=${MODE}
            - QUEUE_NAME=${QUEUE_NAME}
            - QUEUE_REDIS_EVENT_STREAM_MAX_LEN=${QUEUE_REDIS_EVENT_STREAM_MAX_LEN}
            - WORKER_CONCURRENCY=${WORKER_CONCURRENCY}
            - REMOVE_ON_AGE=${REMOVE_ON_AGE}
            - REMOVE_ON_COUNT=${REMOVE_ON_COUNT}
            - REDIS_URL=${REDIS_URL}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_USERNAME=${REDIS_USERNAME}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_TLS=${REDIS_TLS}
            - REDIS_CERT=${REDIS_CERT}
            - REDIS_KEY=${REDIS_KEY}
            - REDIS_CA=${REDIS_CA}
            - REDIS_KEEP_ALIVE=${REDIS_KEEP_ALIVE}
            - ENABLE_BULLMQ_DASHBOARD=${ENABLE_BULLMQ_DASHBOARD}

            # SECURITY
            - CUSTOM_MCP_SECURITY_CHECK=${CUSTOM_MCP_SECURITY_CHECK}
            - CUSTOM_MCP_PROTOCOL=${CUSTOM_MCP_PROTOCOL}
            - HTTP_DENY_LIST=${HTTP_DENY_LIST}
            - TRUST_PROXY=${TRUST_PROXY}

            # DOCUMENT LOADERS
            - PUPPETEER_EXECUTABLE_FILE_PATH=${PUPPETEER_EXECUTABLE_FILE_PATH}
            - PLAYWRIGHT_EXECUTABLE_FILE_PATH=${PLAYWRIGHT_EXECUTABLE_FILE_PATH}

            # MAIN DATABASE CONFIGURATION
            - MAIN_DB_HOST=${MAIN_DB_HOST}
            - MAIN_DB_PORT=${MAIN_DB_PORT}
            - MAIN_DB_DATABASE=${MAIN_DB_DATABASE}
            - MAIN_DB_USER=${MAIN_DB_USER}
            - MAIN_DB_PASSWORD=${MAIN_DB_PASSWORD}
            - MAIN_DB_TYPE=${MAIN_DB_TYPE}
            - DB_POOL_SIZE=${DB_POOL_SIZE}
            - DB_SSL=${DB_SSL}
            - ENABLE_TABLE_CREATION=${ENABLE_TABLE_CREATION}

            # KODIVIAN SERVER MIGRATION
            - APPBUILDER_SHORT_CODE=${APPBUILDER_SHORT_CODE}
            - APPDESIGNER_SHORT_CODE=${APPDESIGNER_SHORT_CODE}
            - APPPUBLISHER_SHORT_CODE=${APPPUBLISHER_SHORT_CODE}

            # REDIS CONFIGURATION
            - REDIS_DB_SESSION=${REDIS_DB_SESSION:-1}
            - REDIS_DB_QUEUE=${REDIS_DB_QUEUE:-3}

            # SERVER CONFIGURATION
            - SERVER_MODE=${SERVER_MODE}
            - SERVER_CLUSTER_MODE=${SERVER_CLUSTER_MODE}
            - SERVER_INSTANCES=${SERVER_INSTANCES}
            - SERVER_TARGET_SERVER=${SERVER_TARGET_SERVER}
            - SERVER_DEPLOY_PATH=${SERVER_DEPLOY_PATH}

            # SESSION CONFIGURATION
            - SESSION_COOKIE_MAX_AGE=${SESSION_COOKIE_MAX_AGE:-900}
            - SESSION_COOKIE_DOMAIN=${SESSION_COOKIE_DOMAIN}
            - SESSION_COOKIE_PATH=${SESSION_COOKIE_PATH:-/}
            - SESSION_COOKIE_HTTP_ONLY=${SESSION_COOKIE_HTTP_ONLY:-true}
            - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-false}
            - SESSION_COOKIE_SAME_SITE=${SESSION_COOKIE_SAME_SITE:-lax}

            # LICENSE AND ENCRYPTION
            - LICENSE_CODE=${LICENSE_CODE}
            - SIMPLE_CRYPTO_KEY=${SIMPLE_CRYPTO_KEY}

            # COUCHDB CONFIGURATION
            - COUCHDB_DATABASE_CONFIG=${COUCHDB_DATABASE_CONFIG:-config}
            - COUCHDB_DATABASE_MAIN_DATA=${COUCHDB_DATABASE_MAIN_DATA:-mobile_platform}
        ports:
            - '${SERVER_PORT:-3030}:${SERVER_PORT:-3030}'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${SERVER_PORT:-3030}/api/v1/ping']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        volumes:
            - ~/.kodivian:/root/.kodivian
        entrypoint: /bin/sh -c "sleep 3; kodivian start"
